language: python
os: linux
dist: bionic
python:
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
    - stage: build docker image
      python: "3.7"
      script:
        - docker build -t traceflow .
        - docker images
        - docker run -p 127.0.0.1:8081:8081 -i -t traceflow 1.1.1.1

install:
  - pip install -r requirements.txt
  - pip install -r requirements-build.txt

script:
  - python setup.py bdist_wheel
  - pip install ./dist/traceflow*any.whl
  - black --check traceflow
  - black --check tests
  - sudo -E $(which pytest)
  - sudo -E $(which traceflow) 1.1.1.1

notifications:
  email: false


